namespace Physics_Data_Debug
{
    partial class FormSuspensionGeometry
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint1 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series2 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint2 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series3 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint3 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series4 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint4 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series5 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint5 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0.329D, 0.12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint6 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(-0.0222D, 0.136D);
            System.Windows.Forms.DataVisualization.Charting.Series series6 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint7 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0.329D, 0.12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint8 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(-0.0222D, 0.136D);
            System.Windows.Forms.DataVisualization.Charting.Series series7 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint9 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint10 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series8 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint11 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint12 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series9 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint13 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint14 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series10 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint15 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint16 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series11 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint17 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint18 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series12 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint19 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint20 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint21 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series13 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint22 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint23 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series14 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint24 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series15 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint25 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint26 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series16 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint27 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint28 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series17 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint29 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint30 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series18 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint31 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint32 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series19 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint33 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint34 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series20 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint35 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint36 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series21 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint37 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint38 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series22 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint39 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint40 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint41 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Series series23 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint42 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint43 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 0D);
            System.Windows.Forms.DataVisualization.Charting.Title title1 = new System.Windows.Forms.DataVisualization.Charting.Title();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.textBox_FL_SuspensionGeometry = new System.Windows.Forms.TextBox();
            this.textBox_FR_SuspensionGeometry = new System.Windows.Forms.TextBox();
            this.textBox_RL_SuspensionGeometry = new System.Windows.Forms.TextBox();
            this.textBox_RR_SuspensionGeometry = new System.Windows.Forms.TextBox();
            this.chart1 = new System.Windows.Forms.DataVisualization.Charting.Chart();
            ((System.ComponentModel.ISupportInitialize)(this.chart1)).BeginInit();
            this.SuspendLayout();
            // 
            // timer1
            // 
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // textBox_FL_SuspensionGeometry
            // 
            this.textBox_FL_SuspensionGeometry.BackColor = System.Drawing.Color.Black;
            this.textBox_FL_SuspensionGeometry.Enabled = false;
            this.textBox_FL_SuspensionGeometry.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox_FL_SuspensionGeometry.ForeColor = System.Drawing.Color.White;
            this.textBox_FL_SuspensionGeometry.Location = new System.Drawing.Point(13, 1396);
            this.textBox_FL_SuspensionGeometry.Margin = new System.Windows.Forms.Padding(4);
            this.textBox_FL_SuspensionGeometry.Multiline = true;
            this.textBox_FL_SuspensionGeometry.Name = "textBox_FL_SuspensionGeometry";
            this.textBox_FL_SuspensionGeometry.ReadOnly = true;
            this.textBox_FL_SuspensionGeometry.Size = new System.Drawing.Size(490, 3564);
            this.textBox_FL_SuspensionGeometry.TabIndex = 243;
            this.textBox_FL_SuspensionGeometry.Visible = false;
            this.textBox_FL_SuspensionGeometry.WordWrap = false;
            // 
            // textBox_FR_SuspensionGeometry
            // 
            this.textBox_FR_SuspensionGeometry.BackColor = System.Drawing.Color.Black;
            this.textBox_FR_SuspensionGeometry.Enabled = false;
            this.textBox_FR_SuspensionGeometry.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox_FR_SuspensionGeometry.ForeColor = System.Drawing.Color.White;
            this.textBox_FR_SuspensionGeometry.Location = new System.Drawing.Point(511, 1396);
            this.textBox_FR_SuspensionGeometry.Margin = new System.Windows.Forms.Padding(4);
            this.textBox_FR_SuspensionGeometry.Multiline = true;
            this.textBox_FR_SuspensionGeometry.Name = "textBox_FR_SuspensionGeometry";
            this.textBox_FR_SuspensionGeometry.ReadOnly = true;
            this.textBox_FR_SuspensionGeometry.Size = new System.Drawing.Size(490, 3564);
            this.textBox_FR_SuspensionGeometry.TabIndex = 245;
            this.textBox_FR_SuspensionGeometry.Visible = false;
            this.textBox_FR_SuspensionGeometry.WordWrap = false;
            // 
            // textBox_RL_SuspensionGeometry
            // 
            this.textBox_RL_SuspensionGeometry.BackColor = System.Drawing.Color.Black;
            this.textBox_RL_SuspensionGeometry.Enabled = false;
            this.textBox_RL_SuspensionGeometry.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox_RL_SuspensionGeometry.ForeColor = System.Drawing.Color.White;
            this.textBox_RL_SuspensionGeometry.Location = new System.Drawing.Point(1009, 1396);
            this.textBox_RL_SuspensionGeometry.Margin = new System.Windows.Forms.Padding(4);
            this.textBox_RL_SuspensionGeometry.Multiline = true;
            this.textBox_RL_SuspensionGeometry.Name = "textBox_RL_SuspensionGeometry";
            this.textBox_RL_SuspensionGeometry.ReadOnly = true;
            this.textBox_RL_SuspensionGeometry.Size = new System.Drawing.Size(490, 3564);
            this.textBox_RL_SuspensionGeometry.TabIndex = 244;
            this.textBox_RL_SuspensionGeometry.Visible = false;
            this.textBox_RL_SuspensionGeometry.WordWrap = false;
            // 
            // textBox_RR_SuspensionGeometry
            // 
            this.textBox_RR_SuspensionGeometry.BackColor = System.Drawing.Color.Black;
            this.textBox_RR_SuspensionGeometry.Enabled = false;
            this.textBox_RR_SuspensionGeometry.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox_RR_SuspensionGeometry.ForeColor = System.Drawing.Color.White;
            this.textBox_RR_SuspensionGeometry.Location = new System.Drawing.Point(1507, 1396);
            this.textBox_RR_SuspensionGeometry.Margin = new System.Windows.Forms.Padding(4);
            this.textBox_RR_SuspensionGeometry.Multiline = true;
            this.textBox_RR_SuspensionGeometry.Name = "textBox_RR_SuspensionGeometry";
            this.textBox_RR_SuspensionGeometry.ReadOnly = true;
            this.textBox_RR_SuspensionGeometry.Size = new System.Drawing.Size(490, 3564);
            this.textBox_RR_SuspensionGeometry.TabIndex = 246;
            this.textBox_RR_SuspensionGeometry.Visible = false;
            this.textBox_RR_SuspensionGeometry.WordWrap = false;
            // 
            // chart1
            // 
            this.chart1.BackColor = System.Drawing.Color.Silver;
            chartArea1.AxisX.Interval = 0.5D;
            chartArea1.AxisX.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisX.MajorGrid.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisX.MajorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            chartArea1.AxisX.MajorTickMark.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisX.Maximum = 2D;
            chartArea1.AxisX.Minimum = -2D;
            chartArea1.AxisX.MinorGrid.Enabled = true;
            chartArea1.AxisX.MinorGrid.LineColor = System.Drawing.Color.Gray;
            chartArea1.AxisX.MinorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dot;
            chartArea1.AxisX.MinorTickMark.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisX2.MajorGrid.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisX2.MajorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            chartArea1.AxisY.Crossing = 0D;
            chartArea1.AxisY.Interval = 0.5D;
            chartArea1.AxisY.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisY.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            chartArea1.AxisY.MajorGrid.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisY.MajorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            chartArea1.AxisY.MajorTickMark.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisY.Maximum = 2D;
            chartArea1.AxisY.Minimum = -1D;
            chartArea1.AxisY.MinorGrid.Enabled = true;
            chartArea1.AxisY.MinorGrid.LineColor = System.Drawing.Color.Gray;
            chartArea1.AxisY.MinorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dot;
            chartArea1.AxisY.MinorTickMark.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisY2.MajorGrid.LineColor = System.Drawing.Color.DimGray;
            chartArea1.AxisY2.MajorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            chartArea1.BackColor = System.Drawing.Color.Transparent;
            chartArea1.Name = "FrontSuspension";
            this.chart1.ChartAreas.Add(chartArea1);
            legend1.BackColor = System.Drawing.Color.LightGray;
            legend1.Docking = System.Windows.Forms.DataVisualization.Charting.Docking.Bottom;
            legend1.Name = "Legend1";
            this.chart1.Legends.Add(legend1);
            this.chart1.Location = new System.Drawing.Point(13, 13);
            this.chart1.Margin = new System.Windows.Forms.Padding(4);
            this.chart1.Name = "chart1";
            series1.ChartArea = "FrontSuspension";
            series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series1.IsValueShownAsLabel = true;
            series1.LabelFormat = "{0:N2}";
            series1.Legend = "Legend1";
            series1.LegendText = "ComHeight";
            series1.MarkerColor = System.Drawing.Color.Green;
            series1.MarkerSize = 8;
            series1.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series1.Name = "FrontCoMHeight";
            series1.Points.Add(dataPoint1);
            series2.ChartArea = "FrontSuspension";
            series2.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series2.IsValueShownAsLabel = true;
            series2.LabelFormat = "{0:N2}";
            series2.Legend = "Legend1";
            series2.LegendText = "RideHeight";
            series2.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series2.MarkerSize = 8;
            series2.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series2.Name = "FrontRideHeight";
            series2.Points.Add(dataPoint2);
            series3.ChartArea = "FrontSuspension";
            series3.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            series3.IsValueShownAsLabel = true;
            series3.LabelFormat = "{0:N3}";
            series3.Legend = "Legend1";
            series3.LegendText = "RollCenterXY";
            series3.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            series3.MarkerSize = 8;
            series3.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series3.Name = "FrontRollCenterXY";
            series3.Points.Add(dataPoint3);
            series4.ChartArea = "FrontSuspension";
            series4.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series4.Color = System.Drawing.Color.Gray;
            series4.IsValueShownAsLabel = true;
            series4.LabelFormat = "{0:N3}";
            series4.Legend = "Legend1";
            series4.LegendText = "TirePivotXY";
            series4.MarkerBorderColor = System.Drawing.Color.Black;
            series4.MarkerBorderWidth = 2;
            series4.MarkerColor = System.Drawing.Color.Gray;
            series4.MarkerSize = 8;
            series4.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series4.Name = "FrontFLTirePivotXY";
            dataPoint4.IsValueShownAsLabel = true;
            series4.Points.Add(dataPoint4);
            series5.ChartArea = "FrontSuspension";
            series5.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            series5.LabelFormat = "{0:N3}";
            series5.Legend = "Legend1";
            series5.LegendText = "UpperFrontArmXY";
            series5.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            series5.MarkerSize = 4;
            series5.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series5.Name = "FrontFLUpperFrontArmXY";
            dataPoint5.IsValueShownAsLabel = true;
            dataPoint6.IsValueShownAsLabel = false;
            series5.Points.Add(dataPoint5);
            series5.Points.Add(dataPoint6);
            series6.ChartArea = "FrontSuspension";
            series6.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series6.Color = System.Drawing.Color.Red;
            series6.LabelFormat = "{0:N3}";
            series6.Legend = "Legend1";
            series6.LegendText = "UpperRearArmXY";
            series6.MarkerColor = System.Drawing.Color.Red;
            series6.MarkerSize = 4;
            series6.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series6.Name = "FrontFLUpperRearArmXY";
            dataPoint7.IsValueShownAsLabel = true;
            dataPoint8.IsValueShownAsLabel = true;
            series6.Points.Add(dataPoint7);
            series6.Points.Add(dataPoint8);
            series7.ChartArea = "FrontSuspension";
            series7.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series7.Color = System.Drawing.Color.Gray;
            series7.Legend = "Legend1";
            series7.LegendText = "UpperArmMidpointXY";
            series7.MarkerColor = System.Drawing.Color.Gray;
            series7.MarkerSize = 3;
            series7.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series7.Name = "FrontFLUpperArmMidpointXY";
            dataPoint10.Color = System.Drawing.Color.Transparent;
            dataPoint10.MarkerColor = System.Drawing.Color.Transparent;
            series7.Points.Add(dataPoint9);
            series7.Points.Add(dataPoint10);
            series8.ChartArea = "FrontSuspension";
            series8.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            series8.LabelFormat = "{0:N3}";
            series8.Legend = "Legend1";
            series8.LegendText = "LowerFrontArmXY";
            series8.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            series8.MarkerSize = 4;
            series8.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series8.Name = "FrontFLLowerFrontArmXY";
            dataPoint11.IsValueShownAsLabel = true;
            dataPoint12.IsValueShownAsLabel = false;
            series8.Points.Add(dataPoint11);
            series8.Points.Add(dataPoint12);
            series9.ChartArea = "FrontSuspension";
            series9.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series9.Color = System.Drawing.Color.Yellow;
            series9.LabelFormat = "{0:N3}";
            series9.Legend = "Legend1";
            series9.LegendText = "LowerRearArmXY";
            series9.MarkerColor = System.Drawing.Color.Yellow;
            series9.MarkerSize = 4;
            series9.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series9.Name = "FrontFLLowerRearArmXY";
            dataPoint13.IsValueShownAsLabel = true;
            dataPoint14.IsValueShownAsLabel = true;
            series9.Points.Add(dataPoint13);
            series9.Points.Add(dataPoint14);
            series10.ChartArea = "FrontSuspension";
            series10.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series10.Color = System.Drawing.Color.Gray;
            series10.Legend = "Legend1";
            series10.LegendText = "LowerArmMidpointXY";
            series10.MarkerColor = System.Drawing.Color.Gray;
            series10.MarkerSize = 3;
            series10.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series10.Name = "FrontFLLowerArmMidpointXY";
            dataPoint16.Color = System.Drawing.Color.Transparent;
            dataPoint16.MarkerColor = System.Drawing.Color.Transparent;
            series10.Points.Add(dataPoint15);
            series10.Points.Add(dataPoint16);
            series11.ChartArea = "FrontSuspension";
            series11.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series11.Color = System.Drawing.Color.Aqua;
            series11.LabelFormat = "{0:N3}";
            series11.Legend = "Legend1";
            series11.LegendText = "SteeringRodXY";
            series11.MarkerColor = System.Drawing.Color.Aqua;
            series11.MarkerSize = 4;
            series11.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series11.Name = "FrontFLSteeringRodXY";
            dataPoint17.IsValueShownAsLabel = true;
            dataPoint18.IsValueShownAsLabel = true;
            series11.Points.Add(dataPoint17);
            series11.Points.Add(dataPoint18);
            series12.ChartArea = "FrontSuspension";
            series12.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series12.Color = System.Drawing.Color.Gray;
            series12.LabelFormat = "{0:N3}";
            series12.Legend = "Legend1";
            series12.LegendText = "InstantCenterXY";
            series12.Name = "FrontFLInstantCenterXY";
            dataPoint20.IsValueShownAsLabel = true;
            dataPoint20.MarkerColor = System.Drawing.Color.Maroon;
            dataPoint20.MarkerSize = 10;
            dataPoint20.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series12.Points.Add(dataPoint19);
            series12.Points.Add(dataPoint20);
            series12.Points.Add(dataPoint21);
            series13.ChartArea = "FrontSuspension";
            series13.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            series13.Legend = "Legend1";
            series13.LegendText = "RCLine";
            series13.Name = "FrontFLRCLine";
            series13.Points.Add(dataPoint22);
            series13.Points.Add(dataPoint23);
            series14.ChartArea = "FrontSuspension";
            series14.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series14.Color = System.Drawing.Color.Gray;
            series14.IsValueShownAsLabel = true;
            series14.IsVisibleInLegend = false;
            series14.LabelFormat = "{0:N3}";
            series14.Legend = "Legend1";
            series14.MarkerBorderColor = System.Drawing.Color.Black;
            series14.MarkerBorderWidth = 2;
            series14.MarkerColor = System.Drawing.Color.Gray;
            series14.MarkerSize = 8;
            series14.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series14.Name = "FrontFRTirePivotXY";
            series14.Points.Add(dataPoint24);
            series15.ChartArea = "FrontSuspension";
            series15.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            series15.IsVisibleInLegend = false;
            series15.LabelFormat = "{0:N3}";
            series15.Legend = "Legend1";
            series15.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            series15.MarkerSize = 4;
            series15.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series15.Name = "FrontFRUpperFrontArmXY";
            dataPoint25.IsValueShownAsLabel = true;
            dataPoint26.IsValueShownAsLabel = false;
            series15.Points.Add(dataPoint25);
            series15.Points.Add(dataPoint26);
            series16.ChartArea = "FrontSuspension";
            series16.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series16.Color = System.Drawing.Color.Red;
            series16.IsVisibleInLegend = false;
            series16.LabelFormat = "{0:N3}";
            series16.Legend = "Legend1";
            series16.MarkerColor = System.Drawing.Color.Red;
            series16.MarkerSize = 4;
            series16.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series16.Name = "FrontFRUpperRearArmXY";
            dataPoint27.IsValueShownAsLabel = true;
            dataPoint28.IsValueShownAsLabel = true;
            series16.Points.Add(dataPoint27);
            series16.Points.Add(dataPoint28);
            series17.ChartArea = "FrontSuspension";
            series17.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series17.Color = System.Drawing.Color.Gray;
            series17.IsVisibleInLegend = false;
            series17.Legend = "Legend1";
            series17.MarkerColor = System.Drawing.Color.Gray;
            series17.MarkerSize = 3;
            series17.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series17.Name = "FrontFRUpperArmMidpointXY";
            dataPoint30.Color = System.Drawing.Color.Transparent;
            dataPoint30.MarkerColor = System.Drawing.Color.Transparent;
            series17.Points.Add(dataPoint29);
            series17.Points.Add(dataPoint30);
            series18.ChartArea = "FrontSuspension";
            series18.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            series18.IsVisibleInLegend = false;
            series18.LabelFormat = "{0:N3}";
            series18.Legend = "Legend1";
            series18.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            series18.MarkerSize = 4;
            series18.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series18.Name = "FrontFRLowerFrontArmXY";
            dataPoint31.IsValueShownAsLabel = true;
            dataPoint32.IsValueShownAsLabel = false;
            series18.Points.Add(dataPoint31);
            series18.Points.Add(dataPoint32);
            series19.ChartArea = "FrontSuspension";
            series19.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series19.Color = System.Drawing.Color.Yellow;
            series19.IsVisibleInLegend = false;
            series19.LabelFormat = "{0:N3}";
            series19.Legend = "Legend1";
            series19.MarkerColor = System.Drawing.Color.Yellow;
            series19.MarkerSize = 4;
            series19.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series19.Name = "FrontFRLowerRearArmXY";
            dataPoint33.IsValueShownAsLabel = true;
            dataPoint34.IsValueShownAsLabel = true;
            series19.Points.Add(dataPoint33);
            series19.Points.Add(dataPoint34);
            series20.ChartArea = "FrontSuspension";
            series20.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series20.Color = System.Drawing.Color.Gray;
            series20.IsVisibleInLegend = false;
            series20.Legend = "Legend1";
            series20.MarkerColor = System.Drawing.Color.Gray;
            series20.MarkerSize = 3;
            series20.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series20.Name = "FrontFRLowerArmMidpointXY";
            dataPoint36.Color = System.Drawing.Color.Transparent;
            dataPoint36.MarkerColor = System.Drawing.Color.Transparent;
            series20.Points.Add(dataPoint35);
            series20.Points.Add(dataPoint36);
            series21.ChartArea = "FrontSuspension";
            series21.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series21.Color = System.Drawing.Color.Aqua;
            series21.IsValueShownAsLabel = true;
            series21.IsVisibleInLegend = false;
            series21.LabelFormat = "{0:N3}";
            series21.Legend = "Legend1";
            series21.MarkerColor = System.Drawing.Color.Aqua;
            series21.MarkerSize = 4;
            series21.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series21.Name = "FrontFRSteeringRodXY";
            series21.Points.Add(dataPoint37);
            series21.Points.Add(dataPoint38);
            series22.ChartArea = "FrontSuspension";
            series22.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series22.Color = System.Drawing.Color.Gray;
            series22.IsVisibleInLegend = false;
            series22.LabelFormat = "{0:N3}";
            series22.Legend = "Legend1";
            series22.Name = "FrontFRInstantCenterXY";
            dataPoint40.IsValueShownAsLabel = true;
            dataPoint40.MarkerColor = System.Drawing.Color.Maroon;
            dataPoint40.MarkerSize = 10;
            dataPoint40.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series22.Points.Add(dataPoint39);
            series22.Points.Add(dataPoint40);
            series22.Points.Add(dataPoint41);
            series23.ChartArea = "FrontSuspension";
            series23.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series23.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            series23.IsVisibleInLegend = false;
            series23.Legend = "Legend1";
            series23.Name = "FrontFRRCLine";
            series23.Points.Add(dataPoint42);
            series23.Points.Add(dataPoint43);
            this.chart1.Series.Add(series1);
            this.chart1.Series.Add(series2);
            this.chart1.Series.Add(series3);
            this.chart1.Series.Add(series4);
            this.chart1.Series.Add(series5);
            this.chart1.Series.Add(series6);
            this.chart1.Series.Add(series7);
            this.chart1.Series.Add(series8);
            this.chart1.Series.Add(series9);
            this.chart1.Series.Add(series10);
            this.chart1.Series.Add(series11);
            this.chart1.Series.Add(series12);
            this.chart1.Series.Add(series13);
            this.chart1.Series.Add(series14);
            this.chart1.Series.Add(series15);
            this.chart1.Series.Add(series16);
            this.chart1.Series.Add(series17);
            this.chart1.Series.Add(series18);
            this.chart1.Series.Add(series19);
            this.chart1.Series.Add(series20);
            this.chart1.Series.Add(series21);
            this.chart1.Series.Add(series22);
            this.chart1.Series.Add(series23);
            this.chart1.Size = new System.Drawing.Size(1984, 1375);
            this.chart1.TabIndex = 242;
            this.chart1.Text = "chart1";
            title1.DockedToChartArea = "FrontSuspension";
            title1.IsDockedInsideChartArea = false;
            title1.Name = "FrontSuspension";
            title1.Text = "Front Suspension";
            this.chart1.Titles.Add(title1);
            // 
            // FormSuspensionGeometry
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.BackColor = System.Drawing.Color.Black;
            this.ClientSize = new System.Drawing.Size(2052, 1395);
            this.Controls.Add(this.textBox_FL_SuspensionGeometry);
            this.Controls.Add(this.textBox_FR_SuspensionGeometry);
            this.Controls.Add(this.textBox_RL_SuspensionGeometry);
            this.Controls.Add(this.textBox_RR_SuspensionGeometry);
            this.Controls.Add(this.chart1);
            this.Name = "FormSuspensionGeometry";
            this.Text = "FormSuspensionGeometry";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormSuspensionGeometry_FormClosing);
            this.Load += new System.EventHandler(this.FormSuspensionGeometry_Load);
            ((System.ComponentModel.ISupportInitialize)(this.chart1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.TextBox textBox_FL_SuspensionGeometry;
        private System.Windows.Forms.TextBox textBox_FR_SuspensionGeometry;
        private System.Windows.Forms.TextBox textBox_RL_SuspensionGeometry;
        private System.Windows.Forms.TextBox textBox_RR_SuspensionGeometry;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart1;
    }
}